# Define a global platform for your project
platform :ios, '14.0'

target 'Calculator Notes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calculator Notes
  pod 'AssetsPickerViewController', '2.9.7'
  pod 'DTPhotoViewerController'
  pod 'ImageViewer'
  pod 'NYTPhotoViewer'
  pod 'Google-Mobile-Ads-SDK', '7.69.0'
  pod 'VegaScrollFlowLayout'
  pod 'WLEmptyState'
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Define o target mínimo para iOS 14.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # Excluir arquitetura arm64 no simulador (necessário para Macs Intel)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end

    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
